/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaces.EventManagement;

import Connection.DBconnect;
import com.lowagie.text.Chunk;
import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Element;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.Font;
import java.awt.print.PrinterException;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.table.TableCellRenderer;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Gihan
 */
public class EventHome extends javax.swing.JFrame {
    
    Connection con = null;
    PreparedStatement preparedStatement = null;
    ResultSet rs = null;
    String defaultTime = "00:00:00";

    /**
     * Creates new form EventHome
     */
    public EventHome() {
        initComponents();
        
        //---------set the JFrame to maximize by default on opening-------------
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        //-------------------jtable header font size----------------------------
        jTable1.getTableHeader().setFont(new Font("Perpetua", Font.BOLD, 18));
        jTable1.setRowHeight(50);
        jTable2.getTableHeader().setFont(new Font("Perpetua", Font.BOLD, 18));
        jTable2.setRowHeight(30);
        //--------------------------DB connect----------------------------------
        con = DBconnect.connect();
        //---------------------------tabeload-----------------------------------
        tableloadView();
        tableloadManage();
        
    }
    
    public void tableloadView(){
        
        try {
            String sql = "SELECT id AS Event_ID,type AS Event_Type,address AS Location,date AS Date,start_time AS Starting_Time,end_time AS Ending_Time,order_id AS Order_Reference FROM event";
            preparedStatement = con.prepareStatement(sql);
            rs = preparedStatement.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } 
        catch (Exception e) {
            System.out.println(e);
        }
        
    }
    
    public void tableloadManage(){
        
        try {
            String sql = "SELECT id AS Event_ID,type AS Event_Type,address AS Location,date AS Date,start_time AS Starting_Time,end_time AS Ending_Time,order_id AS Order_Reference FROM event";
            preparedStatement = con.prepareStatement(sql);
            rs = preparedStatement.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
        } 
        catch (Exception e) {
            System.out.println(e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelWelcome = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabelId = new javax.swing.JLabel();
        jLabelType = new javax.swing.JLabel();
        jLabelAddress = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();
        jLabelStartTime = new javax.swing.JLabel();
        jLabelEndTime = new javax.swing.JLabel();
        jLabelOrder = new javax.swing.JLabel();
        jComboBoxEvent = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaAddress = new javax.swing.JTextArea();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        Date date = new Date();
        SpinnerDateModel sm = new SpinnerDateModel(date, null, null, Calendar.HOUR_OF_DAY);
        jSpinner1 = new javax.swing.JSpinner(sm);
        Date date1 = new Date();
        SpinnerDateModel sm1 = new SpinnerDateModel(date1, null, null, Calendar.HOUR_OF_DAY);
        jSpinner2 = new javax.swing.JSpinner(sm1);
        jComboBoxOrder = new javax.swing.JComboBox();
        jButtonAdd = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jLabelIdValue = new javax.swing.JLabel();
        jTextFieldSearch = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jButtonPrint = new javax.swing.JButton();
        jButtonPDF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelWelcome.setFont(new java.awt.Font("Perpetua", 1, 36)); // NOI18N
        jLabelWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWelcome.setText("Welcome to Event Management ");

        jButtonBack.setBackground(java.awt.Color.yellow);
        jButtonBack.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/EventManagement/back.png"))); // NOI18N
        jButtonBack.setText("Back");

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jTable1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1066, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                .addGap(331, 331, 331))
        );

        jTabbedPane1.addTab("View", jPanel1);

        jLabelId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelId.setText("Id");

        jLabelType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelType.setText("Event Type");

        jLabelAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelAddress.setText("Address");

        jLabelDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelDate.setText("Date");

        jLabelStartTime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelStartTime.setText("Starting Time");

        jLabelEndTime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelEndTime.setText("Ending Time");

        jLabelOrder.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelOrder.setText("Order");

        jComboBoxEvent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxEvent.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select an Event", "Wedding", "Birthday Party", "School Function", "University Function", "Office Function" }));

        jTextAreaAddress.setColumns(20);
        jTextAreaAddress.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextAreaAddress.setRows(5);
        jScrollPane2.setViewportView(jTextAreaAddress);

        jXDatePicker1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        JSpinner.DateEditor de = new JSpinner.DateEditor(jSpinner1, "HH:mm:ss");
        jSpinner1.setEditor(de);
        jSpinner1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        JSpinner.DateEditor de1 = new JSpinner.DateEditor(jSpinner2, "HH:mm:ss");
        jSpinner2.setEditor(de1);
        jSpinner2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jComboBoxOrder.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxOrder.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonAdd.setBackground(java.awt.Color.blue);
        jButtonAdd.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jButtonAdd.setForeground(java.awt.Color.white);
        jButtonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/EventManagement/add.png"))); // NOI18N
        jButtonAdd.setText("Add ");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jTable2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable2);

        jButtonUpdate.setBackground(java.awt.Color.orange);
        jButtonUpdate.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jButtonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/EventManagement/update.png"))); // NOI18N
        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonDelete.setBackground(new java.awt.Color(255, 0, 0));
        jButtonDelete.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jButtonDelete.setForeground(java.awt.Color.white);
        jButtonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/EventManagement/remove.png"))); // NOI18N
        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jLabelIdValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelIdValue.setText("Event ID");

        jButtonSearch.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jButtonSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/EventManagement/search.png"))); // NOI18N
        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jButtonClear.setBackground(java.awt.Color.cyan);
        jButtonClear.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jButtonClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/EventManagement/clear.png"))); // NOI18N
        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButtonPrint.setBackground(java.awt.Color.green);
        jButtonPrint.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jButtonPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/EventManagement/print.png"))); // NOI18N
        jButtonPrint.setText("Print");
        jButtonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintActionPerformed(evt);
            }
        });

        jButtonPDF.setBackground(java.awt.Color.orange);
        jButtonPDF.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jButtonPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/EventManagement/pdf.png"))); // NOI18N
        jButtonPDF.setText("PDF");
        jButtonPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelType, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelIdValue)
                            .addComponent(jComboBoxOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSpinner2, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(jButtonPrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(jButtonPDF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jTextFieldSearch)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIdValue))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelType, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonClear, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jButtonPrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPDF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Manage", jPanel2);

        jScrollPane1.setViewportView(jTabbedPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(26, 26, 26)
                        .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1118, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jButtonBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        
        String Type = jComboBoxEvent.getSelectedItem().toString();
        String Address = jTextAreaAddress.getText();
        //--------------------converting date format----------------------------
        Date Date = jXDatePicker1.getDate();      
        DateFormat DateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String FormatedDate = DateFormat.format(Date);
        //----------------converting starting time format-----------------------
        SimpleDateFormat TimeFormat = new SimpleDateFormat("HH:mm:ss");
        String STime = TimeFormat.format(jSpinner1.getValue());
        //----------------converting ending time format-------------------------
        SimpleDateFormat TimeFormat1 = new SimpleDateFormat("HH:mm:ss");
        String ETime = TimeFormat1.format(jSpinner2.getValue());
        String Order = jComboBoxOrder.getSelectedItem().toString();
        
        try {
            String addEvent = "INSERT INTO event(type,address,date,start_time,end_time,order_id) VALUES('"+Type+"','"+Address+"','"+FormatedDate+"','"+STime+"','"+ETime+"','"+Order+"')";
            preparedStatement = con.prepareStatement(addEvent);
            preparedStatement.execute();
            //refresh table
            tableloadView();
            tableloadManage();
            //set field values null
            jComboBoxEvent.setSelectedIndex(0);
            jTextAreaAddress.setText(null);
            jXDatePicker1.setDate(null);
            //set jspinner1 value to 00:00:00
            Date StartTime = new SimpleDateFormat("HH:mm:ss").parse(defaultTime);
            jSpinner1.setValue(StartTime);
            //set jspinner2 value to 00:00:00
            Date EndTime = new SimpleDateFormat("HH:mm:ss").parse(defaultTime);
            jSpinner2.setValue(EndTime);
            jComboBoxOrder.setSelectedIndex(0);
        } catch (Exception e) {
            System.out.println(e);
        }
        
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        
        String Id = jLabelIdValue.getText();
        int x = JOptionPane.showConfirmDialog(null,"You Are About To Update Event "+Id+". Are You Sure?");
        
        if(x == 0){
            String Type = jComboBoxEvent.getSelectedItem().toString();
            String Address = jTextAreaAddress.getText();
            //--------------------converting date format----------------------------
            Date Date = jXDatePicker1.getDate();      
            DateFormat DateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String FormatedDate = DateFormat.format(Date);
            //----------------converting starting time format-----------------------
            SimpleDateFormat TimeFormat = new SimpleDateFormat("HH:mm:ss");
            String STime = TimeFormat.format(jSpinner1.getValue());
            //----------------converting ending time format-------------------------
            SimpleDateFormat TimeFormat1 = new SimpleDateFormat("HH:mm:ss");
            String ETime = TimeFormat1.format(jSpinner2.getValue());
            String Order = jComboBoxOrder.getSelectedItem().toString();
            
            try {
                String updateEvent = "UPDATE event SET id='"+Id+"',type='"+Type+"',address='"+Address+"',date='"+FormatedDate+"',start_time='"+STime+"',end_time='"+ETime+"',order_id='"+Order+"' WHERE id='"+Id+"'";
                preparedStatement = con.prepareStatement(updateEvent);
                preparedStatement.execute();
                
                //refresh table
                tableloadView();
                tableloadManage();
                //set field values null
                jComboBoxEvent.setSelectedIndex(0);
                jTextAreaAddress.setText(null);
                jXDatePicker1.setDate(null);
                //set jspinner1 value to 00:00:00
                Date StartTime = new SimpleDateFormat("HH:mm:ss").parse(defaultTime);
                jSpinner1.setValue(StartTime);
                //set jspinner2 value to 00:00:00
                Date EndTime = new SimpleDateFormat("HH:mm:ss").parse(defaultTime);
                jSpinner2.setValue(EndTime);
                jComboBoxOrder.setSelectedIndex(0);
                //show success message
                JOptionPane.showMessageDialog(null,"Event "+Id+" Updated Successfully!");
            } 
            catch (Exception e) {
                System.out.println(e);  
            } 
        }
        
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        
        String Id = jLabelIdValue.getText();
        int x = JOptionPane.showConfirmDialog(null, "You Are About To Delete Event "+Id+". Are You Sure?");
        
        if(x == 0){
            try {
                String deleteEvent = "DELETE FROM event where id='"+Id+"'";
                preparedStatement = con.prepareStatement(deleteEvent);
                preparedStatement.execute();
                
                //refresh table
                tableloadView();
                tableloadManage();
                //set field values null
                jLabelIdValue.setText("Event ID");
                jComboBoxEvent.setSelectedIndex(0);
                jTextAreaAddress.setText(null);
                jXDatePicker1.setDate(null);
                //set jspinner1 value to 00:00:00
                Date StartTime = new SimpleDateFormat("HH:mm:ss").parse(defaultTime);
                jSpinner1.setValue(StartTime);
                //set jspinner2 value to 00:00:00
                Date EndTime = new SimpleDateFormat("HH:mm:ss").parse(defaultTime);
                jSpinner2.setValue(EndTime);
                jComboBoxOrder.setSelectedIndex(0);
                //show success message
                JOptionPane.showMessageDialog(null,"Event "+Id+" Deleted Successfully!");
            } 
            catch (Exception e) {
                System.out.println(e);
            }
        }
        
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        
        //--------------------selecting row of the table------------------------
        int row = jTable2.getSelectedRow();
        //--------------assigning values of the row to variables----------------
        String Id = jTable2.getValueAt(row, 0).toString();
        String Type = jTable2.getValueAt(row, 1).toString();
        String Address = jTable2.getValueAt(row, 2).toString();
        String Date = jTable2.getValueAt(row, 3).toString();
        String Start_time = jTable2.getValueAt(row, 4).toString();
        String End_time = jTable2.getValueAt(row, 5).toString();
        String Order_id = jTable2.getValueAt(row, 6).toString();
        //-----------------------setting values to fields-----------------------
        jLabelIdValue.setText(Id);
        jComboBoxEvent.setSelectedItem(Type);
        jTextAreaAddress.setText(Address);
        //---setting date to jxdatepicker---
        try {
            Date dateFormat = new SimpleDateFormat("yyyy-MM-dd").parse(Date);
            jXDatePicker1.setDate(dateFormat);
        } catch (Exception e) {
            System.out.println(e);
        }
        //---setting time to jspinner1---
        try {
            Date STime = new SimpleDateFormat("HH:mm:ss").parse(Start_time);
            jSpinner1.setValue(STime);
        } catch (Exception e) {
            System.out.println(e);
        }
        //---setting time to jspinner2---
        try {
            Date ETime = new SimpleDateFormat("HH:mm:ss").parse(End_time);
            jSpinner2.setValue(ETime);
        } catch (Exception e) {
            System.out.println(e);
        }
        jComboBoxOrder.setSelectedItem(Order_id);
         
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        
        String Id = jTextFieldSearch.getText();
        try {
            String searchEvent = "SELECT id AS Event_ID,type AS Event_Type,address AS Location,date AS Date,start_time AS Starting_Time,end_time AS Ending_Time,order_id AS Order_Reference FROM event WHERE id LIKE '%"+Id+"%'";
            preparedStatement = con.prepareStatement(searchEvent);
            rs = preparedStatement.executeQuery();
            
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
        } 
        catch (Exception e) {
            System.out.println(e);
        }
        
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        
        jLabelIdValue.setText("Event ID");
        jComboBoxEvent.setSelectedIndex(0);
        jTextAreaAddress.setText(null);
        jXDatePicker1.setDate(null);
        try {
            //set jspinner1 value to 00:00:00
            Date StartTime = new SimpleDateFormat("HH:mm:ss").parse(defaultTime);
            jSpinner1.setValue(StartTime);
            //set jspinner2 value to 00:00:00
            Date EndTime = new SimpleDateFormat("HH:mm:ss").parse(defaultTime);
            jSpinner2.setValue(EndTime);
        } catch (Exception e) {
            System.out.println(e);
        }
        jComboBoxOrder.setSelectedIndex(0);
        
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintActionPerformed
        
        try {
            boolean print = jTable2.print();
            if (!print) {
                JOptionPane.showMessageDialog(null, "Unable To Print Please Try Again!");
            }
        } catch (PrinterException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
    }//GEN-LAST:event_jButtonPrintActionPerformed

    private void jButtonPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPDFActionPerformed
        
        String path = "";
        JFileChooser jfc = new JFileChooser();
        jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x = jfc.showSaveDialog(this);
        if(x == JFileChooser.APPROVE_OPTION){
            path = jfc.getSelectedFile().getPath();
        }
        Document doc = new Document();
        
        try {
            PdfWriter.getInstance(doc, new FileOutputStream(path+"EventList.pdf"));
            doc.open();
            
            //get currunt date and time
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
            LocalDateTime now = LocalDateTime.now();
            
            //title of the pdf
            Paragraph para = new Paragraph("Helasiritha Event List - Generated On "+dtf.format(now));
            para.setAlignment(Element.ALIGN_CENTER);
            
            doc.add(para);
            
            // add a blank line
            doc.add( Chunk.NEWLINE );
            
            PdfPTable tbl = new PdfPTable(7);
            //table headers
            tbl.addCell("Event ID");
            tbl.addCell("Event Type");
            tbl.addCell("Address");
            tbl.addCell("Date");
            tbl.addCell("Starting Time");
            tbl.addCell("Ending Time");
            tbl.addCell("Order ID");
            
            for(int i = 0; i < jTable2.getRowCount(); i++){
                String Id = jTable2.getValueAt(i, 0).toString();
                String Type = jTable2.getValueAt(i, 1).toString();
                String Address = jTable2.getValueAt(i, 2).toString();
                String Date = jTable2.getValueAt(i, 3).toString();
                String StartTime = jTable2.getValueAt(i, 4).toString();
                String EndTime = jTable2.getValueAt(i, 5).toString();
                String OrderId = jTable2.getValueAt(i, 6).toString();
                
                tbl.addCell(Id);
                tbl.addCell(Type);
                tbl.addCell(Address);
                tbl.addCell(Date);
                tbl.addCell(StartTime);
                tbl.addCell(EndTime);
                tbl.addCell(OrderId);
            }
            doc.add(tbl);
              
        } catch (FileNotFoundException | DocumentException ex) {
            Logger.getLogger(EventHome.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        doc.close();
        JOptionPane.showMessageDialog(null,"PDF Generated Successfully!");
        
//        Document document = new Document();
//        try {
//            PdfWriter.getInstance(document, new FileOutputStream("hello.pdf"));
//            document.open();
//            document.add(new Paragraph("it works man thank you!"));
//        } catch (Exception e) {
//            System.out.println(e);
//        }
//        document.close();
        
    }//GEN-LAST:event_jButtonPDFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonPDF;
    private javax.swing.JButton jButtonPrint;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox jComboBoxEvent;
    private javax.swing.JComboBox jComboBoxOrder;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelEndTime;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelIdValue;
    private javax.swing.JLabel jLabelOrder;
    private javax.swing.JLabel jLabelStartTime;
    private javax.swing.JLabel jLabelType;
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextAreaAddress;
    private javax.swing.JTextField jTextFieldSearch;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    // End of variables declaration//GEN-END:variables
}
